# -*- coding: utf-8 -*-
"""4370lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQOyXjHxxocYL_J7kKC32QkWg9NqW8Y-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import scipy.cluster.hierarchy as hcluster
from sklearn.cluster import AgglomerativeClustering

df= pd.read_csv('/content/customer_segmentation.csv')
df.describe()
df.isna().sum()

df.drop('NumWebVisitsMonth',axis = 1 , inplace = True)

lbl = LabelEncoder()

km = KMeans(n_clusters=3)
df_mall['Education'] = lbl.fit_transform(df_mall['Education'])
y_predicted = km.fit_predict(df_mall[['Year_Birth, Education, Marital_Status, Income, Kidhome, Teenhome, Dt_Customer, Recency, MntWines, MntFruits, MntMeatProducts,MntFishProducts, MntSweetProducts, MntGoldProds, NumDealsPurchases, NumWebPurchases, NumCatalogPurchases' ]])

df_mall['cluster']=y_predicted
print(df_mall.head())

km.cluster_centers_


print(km.cluster_centers_)

df.corr()

sns.pairplot(df)

scaling=StandardScaler()
scaled=scaling.fit_transform(df)

scaled_df=pd.DataFrame(scaled,columns=df.columns)

a=[]
K=range(1,10)
for i in K:
    kmean=KMeans(n_clusters=i)
    kmean.fit(df)
    a.append(kmean.inertia_)

plt.plot(K,a,marker='o')
plt.title('Elbow Method',fontsize=15)
plt.xlabel('Number of clusters',fontsize=15)
plt.ylabel('Sum of Squared distance',fontsize=15)
plt.show()

kmeans = KMeans(n_clusters = 3,random_state = 111)
kmeans.fit(scaled_df)

pd.Series(kmeans.labels_).value_counts()

metrics.silhouette_score(scaled_df, kmeans.labels_)

cluster_labels = kmeans.fit_predict(scaled_df)
preds = kmeans.labels_
kmeans_df = pd.DataFrame(df)
kmeans_df['KMeans_Clusters'] = preds
kmeans_df.head(10)

